//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestResultID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Status { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual User User { get; set; }
    }
}
